import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';

const Main = styled.main``;

const IndexPage: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>Hello World</Main>
    </React.Fragment>
  );
};

export default IndexPage;
